#!/bin/bash

echo "📸 Dashboard Screenshot Capture Guide"
echo "======================================"
echo ""
echo "The dashboard is running at: http://localhost:8080/?mode=proxy"
echo "Login: admin / nerd"
echo ""
echo "Please capture these screenshots manually:"
echo ""
echo "1. Main Dashboard View:"
echo "   - Open http://localhost:8080/?mode=proxy in your browser"
echo "   - Press Cmd+Shift+4, then Space, then click the browser window"
echo "   - Save as: dashboard-main.png"
echo ""
echo "2. Admin Page:"
echo "   - Open http://localhost:8080/admin"
echo "   - Press Cmd+Shift+4, then Space, then click the browser window"
echo "   - Save as: admin-page.png"
echo ""
echo "3. Mobile View (optional):"
echo "   - Resize browser to mobile width (~375px)"
echo "   - Capture as: dashboard-mobile.png"
echo ""
echo "After capturing, move screenshots to docs/images/:"
echo "  mv ~/Desktop/dashboard-*.png ~/Desktop/admin-*.png docs/images/"
echo ""
echo "Then commit:"
echo "  git add docs/images/*.png"
echo "  git commit -m 'Docs: add dashboard screenshots'"
echo "  git push"
echo ""
echo "Opening dashboard in default browser..."
cd "$(dirname "$0")/.." && open "http://localhost:8080/?mode=proxy"
